apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-secure-app
  labels:
    app: my-secure-app
spec:
  replicas: 2 # รันแอปพลิเคชันพร้อมกัน 2 ตัว (Pod) เพื่อช่วยกันกระจายโหลด
  selector:
    matchLabels:
      app: my-secure-app
  template:
    metadata:
      labels:
        app: my-secure-app
    spec:
      containers:
        - name: web-app
          image: my-secure-app:latest # ดึง Image ที่ Jenkins เพิ่ง Build เสร็จมาใช้งาน
          imagePullPolicy: Never # สั่งให้ดึง Image จากในเครื่อง Colima ตรงๆ ไม่ต้องโหลดจากเน็ต
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-secure-app-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300 # พอร์ตที่คุณจะใช้เปิดเข้าดูหน้าเว็บของแอปพลิเคชันจาก Browser
  selector:
    app: my-secure-app
