apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-secure-app
  labels:
    app: my-secure-app
spec:
  replicas: 2 # รันแอปพลิเคชันพร้อมกัน 2 ตัว (Pod) เพื่อช่วยกันกระจายโหลด
  selector:
    matchLabels:
      app: my-secure-app
  template:
    metadata:
      labels:
        app: my-secure-app
    spec:
      containers:
        - name: web-app
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: my-secure-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30300 # พอร์ตที่คุณจะใช้เปิดเข้าดูหน้าเว็บของแอปพลิเคชันจาก Browser
  selector:
    app: my-secure-app
